# convert_tract_wacs_to_puma.ipynb

Similar to the tract to puma, except this does puma to migpuma aggregation.

In [ ]:
import pandas as pd

In [ ]:
YEAR = 2017

In [ ]:
df = pd.read_csv(f"wac_puma_{YEAR}.csv").set_index("puma")
df.index = df.index.astype("str").str.zfill(7)
df.head()

,TOT_JOBS,JOBS_AGE_29,JOBS_AGE_30_54,JOBS_AGE_55,JOBS_EARN_1250,JOBS_EARN_1251_3333,JOBS_EARN_3334,AGR,EXT,UTL,...,EDU,MED,ENT,FOD,SRV,PUB,JOBS_EDU_NOHS,JOBS_EDU_HS,JOBS_EDU_NOBACH,JOBS_EDU_BACH
puma,,,,,,,,,,,,,,,,,,,,,
0100100,65457,17347,34154,13956,16751,27438,21268,327,205,671,...,5368,8642,512,6493,1224,3114,6367,15886,15785,10072
0100200,53503,11576,29503,12424,10810,16538,26155,513,25,317,...,6841,3310,912,3905,883,3304,4480,11870,12913,12664
0100301,78052,19057,42152,16843,17911,20914,39227,144,62,68,...,4787,4209,644,8403,1261,769,5996,15325,18086,19588
0100302,71799,17583,38760,15456,19020,26195,26584,19,1,603,...,3229,18338,1169,6276,1744,3973,6161,15190,18302,14563
0100400,36988,8958,20085,7945,8844,17100,11044,335,21,456,...,3299,3988,119,2856,477,1770,3995,10033,9017,4985

In [ ]:
puma_migpuma = pd.read_csv("../geometry/equivalencies/puma_migpuma.csv", dtype="str")
puma_migpuma["PUMA"] = puma_migpuma["State"] + puma_migpuma["PUMA"]
puma_migpuma["MIGPUMA"] = puma_migpuma["State"] + puma_migpuma["MIGPUMA"]
puma_migpuma = puma_migpuma.set_index("PUMA")
puma_migpuma.head()

        State  MIGPUMA
PUMA
0100100    01  0100190
0100200    01  0100290
0100301    01  0100290
0100302    01  0100290
0100400    01  0100400

In [4]:
df.index

Index(['0100100', '0100200', '0100301', '0100302', '0100400', '0100500',
       '0100600', '0100700', '0100800', '0100900',
       ...
       '5555102', '5555103', '5570101', '5570201', '5570301', '5600100',
       '5600200', '5600300', '5600400', '5600500'],
      dtype='object', name='puma', length=2336)

In [5]:
df["MIGPUMA"] = puma_migpuma.loc[df.index, "MIGPUMA"]
df.head()

,TOT_JOBS,JOBS_AGE_29,JOBS_AGE_30_54,JOBS_AGE_55,JOBS_EARN_1250,JOBS_EARN_1251_3333,JOBS_EARN_3334,AGR,EXT,UTL,...,MED,ENT,FOD,SRV,PUB,JOBS_EDU_NOHS,JOBS_EDU_HS,JOBS_EDU_NOBACH,JOBS_EDU_BACH,MIGPUMA
puma,,,,,,,,,,,,,,,,,,,,,
0100100,65457,17347,34154,13956,16751,27438,21268,327,205,671,...,8642,512,6493,1224,3114,6367,15886,15785,10072,0100190
0100200,53503,11576,29503,12424,10810,16538,26155,513,25,317,...,3310,912,3905,883,3304,4480,11870,12913,12664,0100290
0100301,78052,19057,42152,16843,17911,20914,39227,144,62,68,...,4209,644,8403,1261,769,5996,15325,18086,19588,0100290
0100302,71799,17583,38760,15456,19020,26195,26584,19,1,603,...,18338,1169,6276,1744,3973,6161,15190,18302,14563,0100290
0100400,36988,8958,20085,7945,8844,17100,11044,335,21,456,...,3988,119,2856,477,1770,3995,10033,9017,4985,0100400

In [6]:
df_MIGPUMA = df.groupby("MIGPUMA").sum()
df_MIGPUMA.head()

,TOT_JOBS,JOBS_AGE_29,JOBS_AGE_30_54,JOBS_AGE_55,JOBS_EARN_1250,JOBS_EARN_1251_3333,JOBS_EARN_3334,AGR,EXT,UTL,...,EDU,MED,ENT,FOD,SRV,PUB,JOBS_EDU_NOHS,JOBS_EDU_HS,JOBS_EDU_NOBACH,JOBS_EDU_BACH
MIGPUMA,,,,,,,,,,,,,,,,,,,,,
0100190,98529,25250,51644,21635,25062,41438,32029,779,432,1269,...,8608,14647,625,9351,1962,4910,9455,24292,24304,15228
0100290,245485,59460,132801,53224,57826,83060,104599,861,148,1392,...,17766,30295,2984,22751,4707,9464,21545,52341,59277,52862
0100400,36988,8958,20085,7945,8844,17100,11044,335,21,456,...,3299,3988,119,2856,477,1770,3995,10033,9017,4985
0100600,54389,12461,30161,11767,12460,19939,21990,220,82,435,...,3884,6261,324,4793,1075,2062,5395,13647,13970,8916
0100700,36722,9555,19259,7908,8776,16409,11537,418,6,270,...,2961,4641,198,3053,652,1799,3442,9382,9094,5249

In [ ]:
df_MIGPUMA.to_csv(f"wac_migpuma_{YEAR}.csv")